server:
  port: 8087

spring:
  application:
    name: transaction-service
  datasource:
    url: ${TRANSACTION_DB_URL}
    username: ${TRANSACTION_DB_USERNAME}
    password: ${TRANSACTION_DB_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

security:
  jwt:
    secret: ${JWT_SECRET}

services:
  internal-api-key: ${INTERNAL_API_KEY}

springdoc:
  swagger-ui:
    path: /swagger-ui

logging:
  level:
    com.oracle.banking.transaction: INFO
