package com.oracle.banking.workflow.entity;

public enum WorkflowStatus {
    STARTED,
    PREREQUISITES_VALIDATED,
    ACCOUNT_CREATED,
    BILL_PAYMENT_CREATED,
    LOAN_REPAYMENT_CREATED,
    SOURCE_MOVED,
    DESTINATION_MOVED,
    TRANSACTIONS_RECORDED,
    COMPLETED,
    COMPENSATING,
    COMPENSATED,
    COMPENSATION_PENDING,
    FAILED
}
