server:
  port: 8084

spring:
  application:
    name: branch-service
  datasource:
    url: ${BRANCH_DB_URL}
    username: ${BRANCH_DB_USERNAME}
    password: ${BRANCH_DB_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

security:
  jwt:
    secret: ${JWT_SECRET}

services:
  internal-api-key: ${INTERNAL_API_KEY}

springdoc:
  swagger-ui:
    path: /swagger-ui

logging:
  level:
    com.oracle.banking.branch: INFO
