server:
  port: 8083

spring:
  application:
    name: customer-service
  datasource:
    url: ${CUSTOMER_DB_URL:jdbc:oracle:thin:@localhost:1521/FREEPDB1}
    username: ${CUSTOMER_DB_USERNAME:banking_customer}
    password: ${CUSTOMER_DB_PASSWORD:change-me}
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

security:
  jwt:
    secret: ${JWT_SECRET:MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIzNDU2Nzg5MDE=}

services:
  internal-api-key: ${INTERNAL_API_KEY:replace-this-before-production}

kyc:
  encryption-key: ${KYC_ENCRYPTION_KEY}

springdoc:
  swagger-ui:
    path: /swagger-ui

logging:
  level:
    com.oracle.banking.customer: INFO
