server:
  port: 8090

spring:
  application:
    name: billpayment-service
  datasource:
    url: ${BILLPAYMENT_DB_URL:jdbc:oracle:thin:@localhost:1521/FREEPDB1}
    username: ${BILLPAYMENT_DB_USERNAME:BANKING}
    password: ${BILLPAYMENT_DB_PASSWORD:change-me}
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

security:
  jwt:
    secret: ${JWT_SECRET:MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIzNDU2Nzg5MDE=}

services:
  internal-api-key: ${INTERNAL_API_KEY:replace-this-before-production}

springdoc:
  swagger-ui:
    path: /swagger-ui

logging:
  level:
    com.oracle.banking.billpayment: INFO
