server:
  port: 8086

spring:
  application:
    name: beneficiary-service
  datasource:
    url: ${BENEFICIARY_DB_URL}
    username: ${BENEFICIARY_DB_USERNAME}
    password: ${BENEFICIARY_DB_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

security:
  jwt:
    secret: ${JWT_SECRET}

services:
  internal-api-key: ${INTERNAL_API_KEY}
  account-service-url: ${ACCOUNT_SERVICE_URL}

springdoc:
  swagger-ui:
    path: /swagger-ui

logging:
  level:
    com.oracle.banking.beneficiary: INFO
